version: '3.5'

services:
  db:
    image: postgres:14.7
    restart: always
    healthcheck:
      test: pg_isready --dbname=star_wars --username=postgres
      interval: 5s
      timeout: 50s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: star_wars
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
    container_name: locakstack
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      # TODO: create queue automatically
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:4566/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  star-wars-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: star-wars-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3000
      - SWAPI_API_URL=https://swapi.tech/api
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/star_wars?schema=public
    ports:
      - '3000:3000'

  star-wars-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: star-wars-frontend
    depends_on:
      - star-wars-api
    environment:
      - VITE_STAR_WARS_API_BASE_URL=http://localhost:3000
    ports:
      - '4173:4173'

volumes:
  pgdata:
  localstack_data:
