version: '3.5'

services:
  db:
    image: postgres:14.7
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: star_wars
    volumes:
      - pgdata:/var/lib/postgresql/data

  star-wars-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: star-wars-api
    depends_on:
      - db
    environment:
      - PORT=3000
    ports:
      - '3000:3000'

volumes:
  pgdata:
